src/CHIPBackend.cc, src/CHIPBackend.hh, src/CHIPBindings.cc, src/CHIPDriver.cc, src/backend/Level0/Level0Backend.cc, src/backend/Level0/Level0Backend.hh, src/backend/OpenCL/CHIPBackendOpenCL.cc, src/backend/OpenCL/CHIPBackendOpenCL.hh, src/backend/OpenCL/SVMemoryRegion.cc
logDebug at CHIP-SPV level
logTrace at Backend level
=> Improved Logging

src/backend/Level0/CHIPBackendLevel0.cc
=> Level0: Fix printf buffers were not flushed

include/hip/devicelib/type_casting_intrinsics.hh, include/hip/spirv_hip_devicelib.hh, src/CHIPBindings.cc
Was required for compiling LAMMPS
=> spirv_hip_devicelib.hh use new files

src/CHIPBindings.cc
=> hipFree call hipDeviceSynchronize

CMakeLists.txt
=> Fix cuspv include + CMAKE_INSTALL_PREFIX override

cmake/hip-config-in.cmake
Fix #195 
icpx will not work, correct?
=> no longer support icpx as the compiler

src/backend/Level0/CHIPBackendLevel0.cc, src/backend/OpenCL/CHIPBackendOpenCL.cc
=> Graceful abort

src/CHIPBackend.cc, src/CHIPBindings.cc, src/backend/Level0/CHIPBackendLevel0.cc, src/backend/OpenCL/CHIPBackendOpenCL.cc, src/backend/OpenCL/CHIPBackendOpenCL.hh
Missing destructor implementations.
=> Destructors

src/backend/OpenCL/CHIPBackendOpenCL.cc
=> OpenCL max 1 device per platform

src/backend/OpenCL/CHIPBackendOpenCL.cc
=> Fix takeOver refcount

cmake/UnitTests.cmake
=> Fix make check

src/spirv.cc
... when possible.
When device code compilation fails at the runtime the build log is lacking the symbol names. For example:
```
CHIP error [TID 1984562] [1674030579.550524982] : ZE Build Log:
error: undefined reference to `'
in function: '' called by kernel: 'repro_kernel(double*, double)'
error: backend compiler failed build.
```
This is caused by dropping OpName instructions overzealously in the SPIR-V modules which is done for working around an issue in CHIP-SPV/chip-spv#48.
Change the workaround code to drop only the OpNames that are needed for the workaround so we see symbol names in build logs.
=> Preserve device symbols for better diagnostics

bitcode/devicelib.cl, cmake/UnitTests.cmake, include/hip/devicelib/type_casting_intrinsics.hh, tests/runtime/CMakeLists.txt, tests/runtime/RegressionTest302.hip
=> Define __longlong_as_double() and __double_as_longlong()

bitcode/devicelib.cl
=> Add ballot declaration for platforms where it's not present

bitcode/devicelib.cl, include/hip/devicelib/sync_and_util.hh, include/hip/hip_bfloat16.h, include/hip/host_defines.h, include/hip/spirv_hip_bfloat16.h, src/CHIPBindings.cc
BF16 import, __warpsync(), minor fixes. These allow to build rocPRIM (my branch of it).
=> rocPRIM fixes

CMakeLists.txt
=> fix unresolved fp16 symbols

cmake/UnitTests.cmake, samples/ccompat/CMakeLists.txt, scripts/check.py
=> minor fixes

samples/ccompat/CMakeLists.txt
... this caused the build to break on Ubuntu 20.04 LTS
=> fix missing -pthread flag in ccompat

src/spirv.cc
... produced invalid SPIR-V binary (function declarations must have import linkage). Also, issue a warning when we encounter imported functions - it's likely that the user has forgotten definitions for device symbols.
This patch is known to fix a JIT issue which includes this compiler error message: "Fails to verify module: Global is external, but doesn't have external or weak linkage!"
=> SPIR-V filter: Fix erased import linkage attribute

samples/hipMultiThreadAddCallback/hipMultiThreadAddCallback.cc, src/backend/Level0/CHIPBackendLevel0.cc, src/backend/OpenCL/CHIPBackendOpenCL.cc
With these obvious-looking fixes and https://github.com/pocl/pocl/issues/1208 my local laptop's test envs pass again.
=> Obvious fixes

cmake/UnitTests.cmake, samples/hip_sycl_interop/hip_sycl_interop.cpp, samples/hip_sycl_interop/hip_sycl_interop.h, samples/hip_sycl_interop/onemkl_gemm_wrapper/onemkl_gemm_wrapper.cpp, samples/hip_sycl_interop_no_buffers/hip_sycl_interop.cpp, samples/hip_sycl_interop_no_buffers/hip_sycl_interop.h, samples/hip_sycl_interop_no_buffers/onemkl_gemm_wrapper_no_buffers/onemkl_gemm_wrapper.cpp
=> Updated samples with opencl interop

cmake/UnitTests.cmake, tests/compiler/TestHipccCompileThenLink
Fixes #411 
Fixes #308 
Closes https://github.com/CHIP-SPV/HIPCC/pull/4
=> HIPCC fixes + rdc

include/hip/spirv_hip_fp16.h, src/CHIPBindings.cc, src/backend/Level0/CHIPBackendLevel0.cc, src/backend/OpenCL/CHIPBackendOpenCL.cc, tests/runtime/TestKernelArgs.hip
Various fixes for issues found when porting hipCUB/rocPRIM.
=> Rocprim fixes 2

tests/compiler/CMakeLists.txt
=> Fix multisource hipcc

cmake/UnitTests.cmake, include/hip/devicelib/atomics.hh, tests/runtime/CMakeLists.txt, tests/runtime/TestKernelArgs.hip, tests/runtime/TestUndefKernelArg.hip
With this rocPRIM builds (once again).
=> Atomic add ulong

llvm_passes/HipPrintf.cpp
A patch that may fix a compiler crash seen in #467. Couldn't reproduce the issue on my machine. According the crash site, it's possible that the HipPrintf pass encounters something unusual and crashes because of it.
=> HipPrintf: Robustize getCalledFunction()

include/hip/spirv_hip_ldg.h, include/hip/spirv_hip_runtime.h, tests/compiler/CMakeLists.txt, tests/compiler/TestLdg.hip
=> Fix missing __ldg functions

CMakeLists.txt
=> Fix install location of hip_version.h

src/spirv.cc, tests/runtime/CMakeLists.txt, tests/runtime/TestRuntimeWarnings.bash, tests/runtime/inputs/MissingDef.hip
=> Don't emit missing definition warnings for builtins

include/hip/devicelib/double_precision/dp_math.hh, tests/runtime/TestStlFunctionsDouble.hip
=> Fix missing __device__ pow(double, double) decl

tests/compiler/CMakeLists.txt, tests/compiler/TestHipccDashX.bash
=> fix -x hip

CMakeLists.txt, cmake/UnitTests.cmake, samples/cuda_samples/CMakeLists.txt, src/CHIPBackend.hh, src/backend/Level0/CHIPBackendLevel0.cc, src/backend/Level0/CHIPBackendLevel0.hh, src/backend/OpenCL/CHIPBackendOpenCL.cc
Fixes #502 
Fixes #409
prepends CHIP-specific CMake options with CHIP_
=> Cmake fixes

tests/compiler/CMakeLists.txt, tests/compiler/TestHipccCompileAndLink.bash, tests/compiler/TestHipccCompileThenLink.bash
=> Fix hipcc tests, compile then link case

src/CHIPBackend.cc
=> Address memory leak in #546

samples/sycl_hip_interop/sycl_hip_interop_driver/sycl_chip_interop.cpp
=> Fix for Interop sample build issue

include/hip/devicelib/atomics.hh, include/hip/devicelib/sync_and_util.hh, include/hip/spirv_fixups.h, include/hip/spirv_hip_devicelib.hh, tests/runtime/TestStlFunctionsDouble.hip
=> Add missing __device__ std::pow overloads

tests/compiler/CMakeLists.txt, tests/compiler/inputs/testIssue606.cpp
Fixes https://github.com/CHIP-SPV/chipStar/issues/606
Fixes https://github.com/CHIP-SPV/chipStar/issues/607
=> HIPCC Fixes

bitcode/devicelib.cl, llvm_passes/CMakeLists.txt, llvm_passes/HipLowerMemset.cpp, llvm_passes/HipLowerMemset.h, llvm_passes/HipPasses.cpp, tests/runtime/CMakeLists.txt, tests/runtime/TestMemFunctions.hip
... by removing volatile keywords in __chip_mem{set,cpy}.
Closes #550.
=> Address performance issue in #550

src/backend/Level0/CHIPBackendLevel0.cc, src/backend/Level0/CHIPBackendLevel0.hh
Replace `std::map` with `chipstar::Event` storage for maintaining relationships between events and command lists
=> Replace command list map with event storage

tests/compiler/CMakeLists.txt, tests/compiler/TestHipcc692Regression.bash
=> Hipcc rewrite

.github/workflows/presubmit.yml
* Add LLVM 15 building and PoCL test
=> Pocl llvm 15

CMakeLists.txt, docs/release_notes/chipStar_1.1.rst, scripts/check.py, scripts/unit_tests.sh, src/Utils.cc
Fixes #715 
* remove `-gdwarf-4`
* getHIPCCPath via dll
* exclude double tests if no support
=> some additional 1.1 fixes (on main)

.github/actions/get-shas/action.yml, .github/workflows/presubmit.yml
Update github runners to do PoCL 5.0 testing
=> Add PoCL  5.0 Testing

src/CHIPBackend.hh, src/backend/Level0/CHIPBackendLevel0.cc, src/backend/Level0/CHIPBackendLevel0.hh, src/backend/OpenCL/CHIPBackendOpenCL.cc, src/backend/OpenCL/CHIPBackendOpenCL.hh, tests/runtime/TestBallot.hip
Also, fix harmless but still wrong hipMemcpy() call. It does device->host copy but it was parametrized with hipMemcpyHostToDevice.
=> Define hasWarpBallot prop, replace hasBallot() with it

llvm_passes/HipSanityChecks.cpp
AFAIK, all HIP atomic operations should map to corresponding OpenCL built-ins. This checker attempts to catch unexpected non-OpenCL atomic built-ins.
=> Add sanity check for catching unexpected atomic built-ins

.github/workflows/presubmit.yml
=> default to Debug 

.github/workflows/check-unit-tests.yml, CMakeLists.txt, llvm_passes/HipGlobalVariables.cpp, llvm_passes/HipKernelArgSpiller.cpp, scripts/configure_llvm.sh, scripts/unit_tests.sh
Updates are currently based on:
* llvm-project: b12a742c20ae548c5d84f1719f9199577b382ccd
* llvm-spirv: 4e9edf69b836eaf0540df9c43ee95d908b2f1f77
=> Adjustments for future LLVM-18 release

include/hip/devicelib/single_precision/sp_math.hh
... for few single-precision HIP built-ins.
=> Fix called incorrect compiler built-ins

llvm_passes/HipPasses.cpp
... so unused ones get removed by DCE passes.
=> Internalize `__device__` functions

README.md, scripts/check.py, scripts/manage_known_failures.py, scripts/unit_tests.sh, src/CHIPBackend.hh, src/CHIPDriver.hh, src/backend/Level0/CHIPBackendLevel0.cc, src/backend/Level0/CHIPBackendLevel0.hh, src/backend/OpenCL/CHIPBackendOpenCL.hh, tests/known_failures.yaml
* Move `Borrowed` template from from OpenCL to `Backend.hh`
* Implement `FencedCmdList` which uses `Borrowed`
* Remove Event - Command list relationship
* Remove `CHIP_L0_IMM_CMD_LISTS` env var
Fixes the remaining of issues specific to Level Zero backend
=> Implement FencedCmdLists

CMakeLists.txt, README.md, cmake/FindLLVM.cmake, docs/Getting_Started.md
* Fix issue which happened on ubuntu when clang is assumed to be in /usr/bin/clang
Fixes #841
Fixes #824
=> Ubuntu Fixes

scripts/compile_libceed.sh, scripts/unit_tests.sh
Add libCEED into the testing flow. LibCEED has hundreds of tests for 3 HIP implementations (reference, shared memory, and hipRTC) as well as the use of hipBLAS.
=> Add libCEED to testing + Update hipBLAS w/sync

scripts/configure_llvm.sh
* Specify C, C++ compilers (needed on ALCF systems)
* Fix a bug with a directory name
=> LLVM Configure script changes

.gitmodules, CMakeLists.txt, README.md, scripts/configure_llvm.sh, spirv-extractor/CMakeLists.txt
Resolves #869 CMake configuration is successfull
=> update configure_llvm for IPO

bin/cucc.py, tests/cuda/CMakeLists.txt
=> handle relocatable code flags cucc

tests/compiler/CMakeLists.txt, tests/compiler/TestDim3Cast.hip
=> Add more implicit casts to dim3

.gitmodules, CMakeLists.txt, README.md
Update modules + changes for hipFFT
=> Enable building of hipFFT

.github/workflows/check-unit-tests-arm.yml, .github/workflows/check-unit-tests-intel.yml, README.md, scripts/check.py, src/CHIPBindings.cc, src/backend/Level0/zeHipErrorConversion.hh, src/backend/OpenCL/CHIPBackendOpenCL.cc, src/backend/OpenCL/CHIPBackendOpenCL.hh, src/backend/OpenCL/clHipErrorConversion.hh, tests/known_failures.yaml
=> OpenCL Backend Fixes

.github/compile-and-cache-main.yml, .github/workflows/nightly-tests.yml, scripts/unit_tests.sh
Add workflows for nightly testing
=> workflows for nightly testing

.github/workflows/check-unit-tests-intel.yml, .github/workflows/compile-and-cache-main.yml, .github/workflows/nightly-tests.yml, .github/workflows/publish-docker.yml, scripts/unit_tests.sh
* Enable nightly (or anytime the CI machine is available) testing. This should help to uncover any flaky tests, race conditions, driver stability issues, etc. 
* Enable build & testing of HipFFT
=> Constantly run tests

.gitmodules, CMakeLists.txt
* add CHIP_BUILD_HIPSOLVER option
=> Integrate hipSOVLER

tests/compiler/CMakeLists.txt, tests/compiler/TestHipcc945MacroSpace.bash
=> Integrate HIPCC macro fix

include/hip/devicelib/atomics.hh
=> implement a missing atomicMax

src/backend/Level0/CHIPBackendLevel0.cc
=> fix L0 caching

include/hip/devicelib/double_precision/dp_math.hh
Fix double precision wrappers so  that they call appropriate functios
=> Fix double precision min/max

CMakeLists.txt
=> install FindHIP.cmake

docker/DockerfileBase
=> Install NEO runtime on docker

src/Utils.cc, src/Utils.hh, src/backend/Level0/CHIPBackendLevel0.cc, src/backend/OpenCL/CHIPBackendOpenCL.cc, tests/runtime/CMakeLists.txt, tests/runtime/TestIGCCaching.hip
=> Add IGC_ flags to kernel caching

src/CHIPBackend.cc, src/CHIPBackend.hh, src/backend/Level0/CHIPBackendLevel0.cc, src/backend/Level0/CHIPBackendLevel0.hh, tests/known_failures.yaml
Create events as needed instead of populating the event pool at the time of creation. 
Initial event pool size of 1000
=> [Level Zero] Lazy Event Creation

scripts/unit_tests.sh, src/CHIPBindings.cc
=> page locking errors

src/backend/Level0/CHIPBackendLevel0.cc, tests/known_failures.yaml
Use copy queue in hipEventRecord
=> EventRecortCopyQueue
