CHIP-SPV/chipStar

- samples/CMakeLists.txt
- src/CHIPBindings.cc
* temporary implementation for hipHostGetDevicePointer returning device pointer same as host pointer
> enable hip-cuda samples

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPDriver.cc
- src/CHIPDriver.hh
- src/backend/Level0/Level0Backend.cc
- src/backend/Level0/Level0Backend.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
* CHIPModule<backend>::compile() should call Backend->get_jit_flags()
* CHIPBackend::get_jit_flags() returns the value of CHIP_JIT_FLAGS if it
is set, otherwise returns CHIPBackend<backend>::get_default_jit_flags()
* each backend must implement
CHIPBackend<backend>::get_default_jit_flags() which returns default JIT
flags
* Level Zero backend does not fail to JIT when a random string is
passed, whereas OpenCL fails to JIT.
> add CHIP_JIT_FLAGS env var

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/backend/Level0/Level0Backend.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
* CHIPEventOpenCL implementation
* Modified HIPCL implementation
* This version is done using cl_event as opposed to cl::Event (I have that one as well) 
* Using cl::Event as was done in HIPCL did not seem to make sense since you often need a handle on the inner cl_event
* Incrementing and decrementing the reference count explicitly is much easier to read (imo) than dealing with cl::Event constructors/destructors
This still needs cleanup and further checks that every enqueue command calls `updateLastEvent()` but this version passed hipEvent sample reporting reasonable timings. 
There's overlap between OpenCL implementation and Level Zero. Further work can be done to implement more logic at the CHIP-SPV level.
> [OpenCL] Implement events

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/backend/Level0/Level0Backend.cc
- src/backend/Level0/Level0Backend.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
* Introduce `CHIPContext::syncQueues()`
* Backend definitions expose wrapped functions to CHIP-SPV bindings. These wrapped functions enforce queue syncronization and last event updates. Backends must implement pure virtual function equivalents
* Enqueue commands now return `CHIPEvents*` 
This is PR 1/2. Next PR will propagate wrappers and `CHIPEvent*` returns. PRs are split for readability.
> Implement queue semantics 1/2

- src/CHIPBackend.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
Fix crash caused by updateLastEvent() being called with an event that
equals to the last event.
> Fix crash in updateLastEvent

- src/CHIPBackend.cc
One of the symptoms due to this was a double free of CHIPEvents which was encountered in #13.
> Fix an exec item was created with an incorrect queue

- CMakeLists.txt
* Make sure HIP LLVM passes are built before HIP programs are
(samples, HIP tests).
* HIP LLVM passes do not depend on the kernel library. Remove the
dependence.
* Make the CHIP module (the runtime) depend on kernel library and HIP
LLVM passes for convenience. HIP compilation depend on all of the three.
The runtime itself does not depend on the kernel library or the passes.
> Adjust build dependences

- src/backend/OpenCL/CHIPBackendOpenCL.cc
Print OpenCL platform info by using logDebug() instead of std::cout. Printing the info to stdout caused `make build_tests_standalone` to create bogus test cases:
```bash
$ ctest -N
...
Test #313: Unit_hipMemset3DAsync_Negative
Test #314: Using Devices of type gpu
Test #315: Found 2 OpenCL platforms:
Test #316: 0. Intel(R) OpenCL HD Graphics
Test #317: 1. Intel(R) CPU Runtime for OpenCL(TM) Applications
Test #318: OpenCL Devices of type gpu with SPIR-V_1 support:
Test #319: Intel(R) HD Graphics 530 [0x1912]
Test #320: OpenCL Context Initialized.
Test #321: Unit_hipMemset3D_RegressInLoop
...
```
> OpenCL: use logDebug() for printing platform info

- CMakeLists.txt
- llvm_passes/HipPasses.cpp
- llvm_passes/HipPrintf.cpp
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
Fix issues introduced in #35 and other things:
* Fix failures due to uninitialized variables and missing checks.
* Add work around for kernels not working if `OptNoneINTEL` is present in the SPIR-V binary. Perhaps there is a bug in Level zero and Intel’s OpenCL?
* Add `-Wall` compilation option when the build mode is `Debug`.
* Fix compiler warnings.
> Various fixes

- bitcode/CMakeLists.txt
- bitcode/_cl_print_str.cl
- llvm_passes/HipPasses.cpp
- llvm_passes/HipPrintf.cpp
- llvm_passes/HipPrintf.h
- samples/CMakeLists.txt
- samples/printf/CMakeLists.txt
- samples/printf/dynamic_str_args.cc
- samples/printf/dynamic_str_args.xstdout
- samples/printf/nop_printfs.cc
- samples/printf/nop_printfs.xstdout
- samples/printf/printf_tests_common.h
- samples/printf/strings.cc
- samples/printf/strings.xstdout
Updates to the printf support with additional unit tests.
This is ready for a review to pull in to main, but please keep the following caveats in mind:
* This needs an new patch to Clang that emits the literal strings to the global address space instead of the generic address space. @linehill is working on putting it to our default Clang branch and to the upstreaming queue.
* Some of the tests fail on L0 which I suspect are issues with the Intel's compiler (yet to confirm). These pass with PoCL's spirv-fixes branch on a CPU device.
* I haven't ran the new unit tests on AMD/HIP so the checks might need updating (I miss a AMD/HIP platform to test on).
> Printf fixes

- samples/hipSymbol/CMakeLists.txt
- samples/hipSymbol/hipTestSymbolReset.cc
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
When hipDeviceReset() is called, reset all global device variables to their initialization value.
> hipDeviceReset(): Clear device global variables.

- src/CHIPBackend.hh
- src/Utils.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
A follow up patch for #32. This brings the texture support to the OpenCL backend to the same level as Level Zero.
> Bring the texture support for OpenCL

- llvm_passes/HipGlobalVariables.cpp
- samples/hipSymbol/CMakeLists.txt
- samples/hipSymbol/hipTestVariableTemplateSymbols.cc
Add support for global scope `__device__` variable templates (https://en.cppreference.com/w/cpp/language/variable_template). These variables are reinitialized on hipDeviceReset() calls.
> Add support for __device__ variable templates

- samples/texture/CMakeLists.txt
- samples/texture/hipAddressingModes.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
* Level0: Set correct texture address mode for hipAddressModeWrap.
* All backends: Ignore hipAddressModeWrap and hipAddressModeMirror and fallback to clamp mode when textures use normalized coordinates.
> Correct texture address modes

- src/CHIPBackend.cc
`RegisteredVarCopy` is a function that takes care of variable transfers to/from host for variables that have been registered via `hipHostRegister`
* No longer block on the host once the transfer has been enqueued since kernel launches are asynchronous, you must manually sync with the host by calling `hipDeviceSyncronize()` or equivalent. This sync would also take care of waiting on these inserted transfers.
* If memory is shared do not perform any transfers.
> Fix host transfer

- src/backend/OpenCL/CHIPBackendOpenCL.cc
This fixes broken tests under samples/hipSymbol/.
The double addition of the CHIPDevice to a CHIPContext caused multiple
CHIPDeviceVar instances per global-scope device variable to be created
in a way that the host and kernels saw different device pointers. This
then caused the host and kernels not to see each other's writes to the
variables.
> OpenCL: Fix duplicate device reference in a context

- samples/hip_sycl_interop/CMakeLists.txt
- samples/hip_sycl_interop/hip_sycl_interop.cpp
- samples/hip_sycl_interop/hip_sycl_interop.h
- samples/hip_sycl_interop_no_buffers/hip_sycl_interop.cpp
- samples/sycl_hip_interop/sycl_chip_interop.h
- samples/sycl_hip_interop/sycl_hip_interop_driver/CMakeLists.txt
- samples/sycl_hip_interop/sycl_hip_interop_driver/sycl_chip_interop.cpp
- samples/sycl_hip_interop/sycl_hip_interop_driver/sycl_chip_interop.h
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/CHIPDriver.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
Creating a separate PR with fixes to HIP-SYCL Interop
* Various compilation issues in the two samples
* One issue that needs to be addressed is SYCL calling HIP:
1. icpx compiler needs to be used to compile SYCL (at least the way that the sample is currently setup) and it is not compatible with HIP headers. Including "hip/hip_runtime.h" results in errors
2. `hipInitFromNativeHandles` Is not in the HIP API, so it must be declared in the sample itself
3. if `hipInitFromNativeHandles` returns `hipError_t` then we must include "hip/hip_runtime.h"
* A lot of formatting/linting issues.
> Fixes to HIP-SYCL Interop

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
* Relax the requirement for queues to always have a last event - let it be null.
* Get rid of `initializeEventPool` since it's not used
* Add `initializeQueueGroupProperties()` to simplify creating queues
* move `getCmdListCopy()` to .cc
> Fix Errors and Refactor Queues

- include/hip/spirv_hip.hh
Suppress the warning to reduce noise.
> Suppress -Wunused-function coming from device side abort()

- CMakeLists.txt
- bitcode/CMakeLists.txt
- llvm_passes/HipPrintf.cpp
* Disable opaque pointers because llvm-spirv does not support them (yet).
* Fix HipPrintf pass triggered a LLVM assertion.
> Fixes for LLVM 15

- src/backend/Level0/CHIPBackendLevel0.cc
... by:
* demoting a "Remaining # events..." messages to debug level as this seems to be an implementation detail which probably is not valuable info for users.
* removing a Level Zero workaround for allocation alignment issue that does not seems to to be around anymore (tested on Intel Compute Runtime 22.30.23789).
Resolves #94.
> Reduce (spurious) warning messages

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
I saw that CHIPStaleEventMonitorLevel0::monitor() was not cleaning up
stale command list (aka. they are memory leaked) which I suspected to
be the cause for memory hogging in tests like FloydWarshall. Attempted
to fix the issue by:
* changing event call method get() -> peek() in
CHIPQueueLevel0::executeCommandList to "fix" reference counting. I
saw in the logs that reference counter was incremented two times but
only ever decreased by one once.
* resetting event state when the reference count decresed to zero so
they could be reused. Without this the recycled events were not put
into Backend->Events lists so the monitor never picked them up.
Also, fixed CHIPStaleEventMonitorLevel0::monitor() not to delete used
events which are belonging to event pools. Apparently, LZEventPool
manages …
> Attempt to fix #101

- bin/CMakeLists.txt
- bin/cuspvc-build.in
- bin/cuspvc-install.in
This makes the cuspvc more convenient to use and fixes one test under tests/cuda/ (which was broken by 5be3db582a217a28c4017480957b9f03138bad4e).
> cuspvc: Add search directory for locating clang++

- .gitmodules
- CHANGES
- README.md
- docs/release_notes/release-0.9.txt
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
With these, the #142 status goes to:
```
97% tests passed, 23 tests failed out of 671
Label Time Summary:
cuda        =  63.34 sec*proc (27 tests)
internal    =  84.68 sec*proc (80 tests)
Total Test time (real) = 665.05 sec
The following tests did not run:
641 - sycl_chip_interop (Skipped)
642 - sycl_chip_interop_usm (Skipped)
The following tests FAILED:
100 - Unit_hipMemcpy_HalfMemCopy (Failed)
127 - Unit_hipMemset_InvalidPtrTests (Failed)
205 - Unit_hipMemcpyAsync_KernelLaunch - int (Failed)
206 - Unit_hipMemcpyAsync_KernelLaunch - float (Failed)
207 - Unit_hipMemcpyAsync_KernelLaunch - double (Failed)
500 - Unit_hipStreamGetFlags_BasicFunctionalities (Failed)
508 - Unit_hipMultiStream_sameDevice (SEGFAULT)
519 - Unit_hipStreamCreate_MultistreamBasicFunctionalities (Failed)
545 - …
```
> Fixes and documentation updates for Release 0.9

- CMakeLists.txt
- bin/cuspvc-build.in
- bin/cuspvc-install.in
- tests/cuda/CMakeLists.txt
This fix requires HIPCC submodule to be updated with fixes from https://github.com/CHIP-SPV/HIPCC/pull/1.
> Fix a test failed after switching to C++-based hipcc

- CMakeLists.txt
- README.md
- samples/CMakeLists.txt
- samples/fp16/CMakeLists.txt
- samples/fp16/half_math.cpp
- samples/hip_sycl_interop/CMakeLists.txt
- samples/hip_sycl_interop_no_buffers/CMakeLists.txt
- samples/sycl_hip_interop/sycl_hip_interop_driver/CMakeLists.txt
* Remove Catch2 submodule as AMD won't integrate it into HIPCOMMON
* Remove `build_tests_standalone` option in favor a CMake OPTION `STANDALONE_TESTS`
* Add CMake option `BUILD_TESTS`
> Remove Catch2 Submodule

- src/CHIPBindings.cc
AFAIU it should not just go and fill the memory as asked in that case, but return an error if it's not an UM-mapped pointer.
Fixes Unit_hipMemset_InvalidPtrTests for OpenCL.
@pvelesko  can you test with the Aurora envs and push this in if works and looks OK? Thanks!
> Fix hipMemset behavior with host malloc'd pointers

- CMakeLists.txt
- Config.hh.in
- include/hip/spirv_hip_fp16.h
- llvm_passes/CMakeLists.txt
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/CHIPException.hh
- src/Filesystem.hh
- src/Utils.cc
- src/Utils.hh
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/common.hh
- src/spirv.cc
- src/spirv_hiprtc.cc
Implement hiprtc API for basic runtime compilation cases
Supported:
* Invoking extern "C" `__global__` kernels.
Unsupported or missing features:
* Compile options (currently ignored).
* Invoking non-extern "C" `__global__` kernels (required `hiprtcAddNameExpression()` and `hiprtcGetLoweredName()` functions are not implemented yet).
> Implement hiprtc API for basic runtime compilation cases

- CMakeLists.txt
- src/Utils.cc
* Fix included <filesystem> instead of one provided by the Filesystem.hh.
* Fix used 'std::filesystem' namespace instead of 'fs' provided by the Filesystem.hh.
Fixes #200.
> Fix filesystem issues

- samples/hipStreamSemantics/hipStreamSemantics.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
The L0 queue initialization was incorrect - always creating a copy queue even when one was unavailable. Fixes #207
> Fix Level Zero Queue initialization

- CMakeLists.txt
- docs/Features.md
- docs/Using.md
- llvm_passes/CMakeLists.txt
- llvm_passes/HipEmitLoweredNames.cpp
- llvm_passes/HipEmitLoweredNames.h
- llvm_passes/HipPasses.cpp
- src/CHIPBackend.hh
- src/Utils.cc
- src/Utils.hh
- src/spirv_hiprtc.cc
- tests/hiprtc/CMakeLists.txt
- tests/hiprtc/TestCommon.hh
- tests/hiprtc/TestHiprtcCPPKernels.cc
- tests/hiprtc/TestHiprtcOptions.cc
* Implements hiprtcAddNameExpression(), hiprtcGetLoweredName() for supporting invocation of C++ kernels. These functions do not support global `__device__` and `__constant__ `variables in this patch.
* hiprtcCompileProgram now accepts some of the user options. This includes --std, -O and -D. All unrecognized options are ignored by default and warnings are given when they are encountered.
TODOs before PR:
> hiprtc: support C++ kernels and handle user options

- llvm_passes/HipEmitLoweredNames.cpp
...error encountered on LLVM 15.
Fixes #217.
> Fix no template named 'optional' in namespace 'std'

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
Remove device and queue vectors from `CHIPBackend` this was originally done for convenience of not having to iterate through contexts->devices->queues to get all the queue handles but this proved to complicate things more than necessary. 
* A few other multithreading related fixes
* Clarify `CHIPBackendLevel0::uninitialize()`
> Remove backend queues

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/CHIPDriver.cc
- tests/hiprtc/TestHiprtcCPPKernels.cc
Missing backend uninitialization at program exit is known to cause crashes occasionally due to monitor threads being still in-flight and making references to destructed objects.
* Fix HIP programs without embedded modules (occasionally) crash at program exit.
* Make sure spdlog is destructed after the CHIP backend is uninitialized.
Fixes #228.
> Fix missing backend uninitialization causes occational crashes

- src/CHIPBindings.cc
During array allocation CHIP-SPV runtime was not including depth hence the memory overflow.
> Fix for #262

- src/CHIPBindings.cc
hipGetNativeHandle assumes that CHIP is already initialized but there can be cases where hipGetNativeHandle is the first call hence CHIPInitialize() need to be called.
> hipGetNativeHandle should call CHIPInitialize()

- bitcode/devicelib.cl
- include/hip/devicelib/single_precision/sp_intrinsics.hh
- include/hip/spirv_hip_devicelib.hh
OpenCL native_* functions have no accuracy quarantees whatsoever whereas the __* math intrinsics of CUDA do. Thus, we cannot use the native functions by default if we want to retain portable correctness in the produced SPIR-Vs.
Fixes cuda-blackscholes for OpenCL/CPU. See Issue #222.
While fixing this, I noticed the builtin library implementation looks a bit messy and has similar codes in two places. What is the idea and longer term plan with it @pvelesko?
> Correctness first with the CUDA math intrinsics

- src/CHIPBindings.cc
... just for fixing undefined reference linker error.
> Add hipProfiler{Start,Stop} without an implementation

- include/hip/spirv_hip_devicelib.hh
This is an undocumented variant of `atomicAdd(float*, float)` without a return value. It is defined in hipamd and a HIP client is known to use it.
> Add atomicAddNoRet(float*, float)

- llvm_passes/HipPasses.cpp
Since the default AS from Clang is generic, this helps getting rid of some unnecessary AS bitcasts.
> Add InferAddressSpaces pass

- CMakeLists.txt
- include/hip/spirv_hip.hh
- include/hip/spirv_hip_host_defines.h
- tests/compiler/CMakeLists.txt
- tests/compiler/TestNoinlineAttrs.hip
- tests/hiprtc/TestCommon.hh
Fix a compiler error caused by C++ libraries (e.g. libstdc++ provided by g++-12) using `__attribute__((__noinline__))` in their code. Our definition of the `__noinline__` appears in the compilation as followed:
```
...
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:37: error: use of undeclared identifier 'noinline'; did you mean 'inline'?
__attribute__((__attribute__((noinline))))
...
```
For Clang <15 this issue is fixed by substituting the `__noinline__` with empty string and, therefore, rendering it ineffective, unfortunately. Fortunately, In Clang >=15 the `__noinline__` is a builtin keyword and the following use cases work in CUDA and HIP language modes:
```
__attribute__((__inline__)) void foo(...);
__inline__ void bar(...);
```
Fixes #138. …
> Fix compiler error with __attribute__((__noinline__))

- samples/hip_sycl_interop/onemkl_gemm_wrapper/onemkl_gemm_wrapper.cpp
- samples/hip_sycl_interop_no_buffers/onemkl_gemm_wrapper_no_buffers/onemkl_gemm_wrapper.cpp
- samples/sycl_hip_interop/sycl_hip_interop_driver/sycl_chip_interop.cpp
Likely doesn't preserve backwards compatibility.
The interop test runs are still skipped for me for some reason:
```
The following tests did not run:
65 - sycl_chip_interop (Skipped)
66 - sycl_chip_interop_usm (Skipped)
```
> Fixes SYCL bindings build for oneAPI 2023.0.0

- tests/compiler/CMakeLists.txt
- tests/compiler/TestAPIObjects.hip
Ensure the case featured in this patch does not regress.
> Add regression test for an ihipEvent_t use case

- src/CHIPBackend.cc
- src/Utils.cc
- src/Utils.hh
- src/spirv.cc
- src/spirv.hh
- tests/runtime/CMakeLists.txt
- tests/runtime/TestKernelArgs.hip
Fix kernel argument passing for aggregates
Fix sizes of aggregate arguments which were not computed correctly causing kernel arguments to be copied partially or copy more bytes than needed to device. The issues found and fixed in the argument size computation logic:
* Array lengths were not extracted from the SPIR-V properly causing random argument sizes.
* The argument size computation logic for structures/arrays did not account alignment requirements of its members/elements.
> Fix kernel argument passing for aggregates

- include/hip/spirv_hip_fp16.h
- include/hip/spirv_hip_vector_types.h
- include/hip/spirv_math_fwd.h
- include/hip/spirv_texture_functions.h
- tests/compiler/CMakeLists.txt
- tests/compiler/TestHipRuntimeHeaderInclude.cpp
Found out that a HIP client includes the `hip_runtime.h` header while compiling the sources in C++ mode by a non-HIP compiler (e.g. g++ in my case). ROCm's HIP supports this but CHIP-SPV does not currently.
Adjust the headers included by the `hip_runtime.h` header so that they are compilable by regular C++ compilers - including the `hipcc` with `-x c++` option.
> Make hip_runtime.h compilable by regular C++ compilers

- include/hip/devicelib/macros.hh
- include/hip/hip_fp16_gcc.h
- include/hip/spirv_hip_fp16.h
- include/hip/spirv_hip_runtime.h
- include/hip/spirv_math_fwd.h
- samples/CMakeLists.txt
- samples/fp16/fp16_conversion.hpp
- samples/fp16/half2_math.cpp
- samples/fp16/half_math.cpp
- samples/fp16/haxpy-base.cpp
- src/CHIPBindings.cc
Also sneak in hipGetStreamDeviceId() implementation.
These updates address some of the first issues encountered while trying to build rocPRIM with CHIP-SPV.
> Copy the latest AMD HIP fp16 implementation

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/hipCtx.hh
Implemented based on HIPAMD. Most of it is unimplemented there as well. 
Main difference is that we now switch from having an active device to having an active context. 
This context is now `thread_local` so resolves some multithreaded tests relied on `hipSetDevice()`
> hipCtx API

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/backend/Level0/CHIPBackendLevel0.cc
* Added assertions to catch invalid/dubious CHIPEvent cases.
* Fixed CHIPEvents being potentially garbage collected too early (see "Fix events possibly being GC'ed too early" commit for details).
> Add asserts for CHIPEvents, fix a potential CHIPEvent error

- CMakeLists.txt
- bitcode/CMakeLists.txt
- bitcode/_cl_print_str.cl
- cmake/LLVMCheck.cmake
- docs/Using.md
- llvm_passes/HipAbort.cpp
- llvm_passes/HipAbort.h
- samples/CMakeLists.txt
- samples/hipDeviceLink/CMakeLists.txt
- src/SPVRegister.cc
- src/common.hh
* Add interface libraries for compiling HIP sources in relocatable device code (RDC) mode. Refer docs/Using.md for instructions.
* Re-enable samples/hipDeviceLink.
* Other adjustments to enable RDC mode.
Upcoming patch part two brings RDC support for hipcc.
Fixes #368.
> Revive RDC mode - part one

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/Utils.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/backend/OpenCL/SVMemoryRegion.cc
- tests/fromLibCeed/firstTouch.cpp
- tests/runtime/CMakeLists.txt
- tests/runtime/TestIndirectMappedHostAlloc.hip
* Fixed RegisterdVarCopy() didn’t synchronize pinned host allocations if the pointers were passed indirectly to kernels. Fixed by synchronizing all pinned host allocations known by the runtime.
* Fixed OpenCL and Level Zero backend drivers were not informed about indirect allocations.
* Fixed a test with false positive test outcome.
Fixes #211.
Closes #386.
> Fix #211 and others

- llvm_passes/HipPrintf.cpp
- tests/compiler/CMakeLists.txt
- tests/compiler/TestPrintfLonePercent.hip
The format string described in #391 has an invalid specifier which triggers undefined behavior. However, The compiler should not crash in such case.
Fixes #391.
> Fix HipPrintf pass crashes on an invalid specifier

- cmake/UnitTests.cmake
It seems that after the oneapi update, these tests are now also getting skipped on Intel HW.
Closes #412
> re-enable managedMem tests

- samples/CMakeLists.txt
- samples/hipStreamSemantics/CMakeLists.txt
- samples/hipStreamSemantics/hipStreamSemantics.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
hipStreamSemantics tests behavior that CUDA callbacks are asynchronously executed in the background whereas OpenCL might or might not execute them in the background. It could execute the callback in the user thread in case the command it is calling back from was finished before the CB was set.
Hack around this by creating a barrier which listens to a user event which is triggered only after setting the CB, forcing parallel execution of the callback. That is, in case the OpenCL platform supports parallel execution of callbacks the first place. I don't believe that's required to be the case, so this is down to implementation still.
Might Fix #421 and #418.
With this my local test envs now pass the expected tests once again.
> OpenCL: Implement CUDA callbacks using OCL CBs and user event hacks

- cmake/UnitTests.cmake
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
* ~~Fix assert that event use after delete (recycled events would not get their `Deleted_` reset~~
* Registered memory map/unmap was not getting applied to async memcpy
* Registered memcopy mapped to `HOST_READ` in all cases instead of `HOST_WRITE` seems that `HOST_WRITE` doesn't guarantee a proper read whereas using `HOST_READ` allows to both write and read host pointers. 
fixes #430
> MemMap Fixes

- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/Utils.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
While running CP2K I could see app crash. It is indicating system is out of memory (OOM) hence the crash. Exact error message is "CHIP error [TID 431805] [1684153005.314770770] : hipErrorTbd (ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY Level Zero Event_ pool creation fail! ) in /nfs/site/home/sarbojit/src/chip-spv/src/backend/Level0/CHIPBackendLevel0.cc:312:CHIPEventLevel0"
I could notice multiple issues in CHIP-SPV event management
Even though hipEventDestroy() was called reference count was always more than 1 hence runtime can't destroy the event. I could reproduce the issue with simple hipEventCreate and hipEventDestroy sample attached here. [hipEvent_test.cc.txt](https://github.com/CHIP-SPV/chip-spv/files/11486904/hipEvent_test.cc.txt)
RT was never destroying event pool handle created as …
> User Event Destruction + EventPool release

- include/hip/devicelib/integer/int_intrinsics.hh
These generate LLVM intrinsics that are compatible the OpenCL popcounts/clz that have return value types matching the operand type, and they are correctly picked up by SPIR-V-translator. Fixes #453.
> Use __builtin_popcount* for popcounts and __builtin_clz* for clz

- include/hip/spirv_hip.hh
- llvm_passes/HipAbort.cpp
- llvm_passes/HipAbort.h
- src/CHIPBindings.cc
- src/SPVRegister.cc
- src/SPVRegister.hh
- tests/runtime/CMakeLists.txt
- tests/runtime/TestAssert.bash
- tests/runtime/TestAssertFail.bash
- tests/runtime/inputs/Assert.hip
- tests/runtime/inputs/AssertFail.hip
... which is needed for assert() being called from device code. Also, some HIP applications calls it directly.
Along the way, fixed HipAbort pass crashing on indirect calls.
Resolves #387.
> Implement `__device__ __assert_fail()`

- bitcode/devicelib.cl
- include/hip/devicelib/double_precision/dp_math.hh
- llvm_passes/CMakeLists.txt
- llvm_passes/HipPasses.cpp
- llvm_passes/HipSanityChecks.cpp
- llvm_passes/HipSanityChecks.h
Starting with checks for:
* indirect calls which are not supported yet.
* caller and callee disagreements on the the function type. (E.g. there is a call to `foo(double)` but the linked-in definition is actually `foo(float)`).
With sanity checks few devicelib issues were fixed:
* Fix return type mismatch on __chip_rnorm_f64().
* Fix call to scalbln(double, long) in OCML but it does not define one.
* Fix call to scalb(double, int) in OCML but second argument type is incorrect.
> Add LLVM pass for sanity checks

- llvm_passes/HipSanityChecks.cpp
... for unsupported indirect call.
> HipSanityCheck: Fix a warning message was not printed

- src/CHIPBackend.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
Fixes a issue found in #467 that caused confusion.
Along the way made sure that all other possibly uninitialized device property fields are defined (although not necessarily correct).
> Fix gcnArchName property is uninitialized

- cmake/UnitTests.cmake
- llvm_passes/HipSanityChecks.cpp
- src/spirv.cc
- tests/runtime/CMakeLists.txt
- tests/runtime/TestIndirectCall.hip
- tests/runtime/TestStructWithFnPtr.hip
Allow/enable device modules with indirect calls to be compiled and run which requires support of SPV_INTEL_function_pointers extension in the driver. Beware, no driver I know expresses support for the extension. Despite this, indirect calls are known to work on Intel Level Zero and Intel OpenCL CPU & GPU (perhaps, by luck). You may try to compile and run TestIndirectCall.hip to see if indirect calls are supported on your system.
Along the way, fixed #462. This patch may also fix #52.
> Add experimental support for indirect calls

- llvm_passes/CMakeLists.txt
- llvm_passes/HipLowerSwitch.cpp
- llvm_passes/HipLowerSwitch.h
- llvm_passes/HipPasses.cpp
- tests/compiler/CMakeLists.txt
- tests/compiler/TestSwitchCase.hip
... with "non-standard" integer bitwidth used as switch value (e.g. i4).
Related issue: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1685.
> Work around llvm-spirv crash on switch instruction

- .gitmodules
- scripts/check.py
- scripts/unit_tests.sh
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
This PR gets rid of our own reference counting and overall event management.
* `CHIPBackend::createCHIPEvent` pure virtual method now expects a return of a `std::shared_ptr<CHIPEvent>
* * There is no option for returning a non-shared event.
* User events are stored in a new vector: `CHIPBackend::UserEvents` - since all events are created as shared_ptr, destroying these events involves taking the raw pointer and looking it up in `CHIPBackend::UserEvents` 
Fixes #477
> Shared ptr events

- CMakeLists.txt
- include/hip/spirv_hip_vector_types.h
- samples/ccompat/CMakeLists.txt
- tests/compiler/CMakeLists.txt
- tests/compiler/TestHostSideHIPVectors.hip
* Fix HIP samples and tests were not recompiled if HIP headers were modified or updated after `git pull` (the ones under include/hip and HIP/include/hip under the source tree). The compilation relied on HIP headers that were copied to build directory with `file(COPY ...)` command which is only executed once after initial configuration.
* Fix no viable overloaded '*=' error on HIP vectors. Only uncommented a region that was commented out in #513 but the changes didn't propagated before the above fix.
Fixes #527.
> Fix no viable overloaded '*=' error on HIP vectors

- cmake/UnitTests.cmake
- src/spirv.cc
Workaround a bug appearing with llvm-spirv-16. The issue is tracked by https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2008.
Fixes LLVM-16 issues in #517. Failures on OpenCL/dGPU are still present.
> Workaround invalid bitcasts of sampled images

- llvm_passes/HipWarps.cpp
This is done to trigger required subgroup size to warp size when there are warp-id-dependent memory accesses in the kernel. This fixes #480 (rocPRIM test_load_warps) for PoCL-CPU.
> Add get_sub_group_load_id() to the warpfuncs

- cmake/hip-config-in.cmake
Fixes #340 
This requirement is being removed because for example, building the shim layer for MKL requires us to incldue hip-config.cmake but also requires us to use Intel compilers thus failing this check.
> remove the hip-config.cmake requirement for clang

- CHIPSPVConfig.hh.in
- CMakeLists.txt
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/backend/OpenCL/SVMemoryRegion.cc
disabled by default, can be enabled with cmake option `-DINTEL_USM_SUPPORT=1`
> add support for Intel USM extension to chipStar OpenCL BE

- .github/actions/get-shas/action.yml
- .github/workflows/presubmit.yml
- scripts/unit_tests.sh
This add a working CI that leverages GitHub actions and pocl to test the OpenCL code path.
- Run is 1h
- Building llvm is a couple of hours, but it is cached
- SPIRV-Tools is apparently unneeded, so we may want to remove it to streamline the workflow.
There are many ways we could improve on it I assume, but at least it demonstrates the feasibility of the approach.
> CI using pocl-cpu.

- .github/actions/get-shas/action.yml
- .github/workflows/presubmit.yml
- scripts/get_sha.sh
- scripts/unit_tests.sh
This does a couple of things:
- Rebuild pocl on llvm changes
- Remove `tee` that was preventing tests from being reported as failed
- Add test of the Intel OpenCL CPU runtime
> Add CI for Intel CPU OpenCL

- src/CHIPBindings.cc
- tests/runtime/CMakeLists.txt
- tests/runtime/TestAPIs.hip
Make it return hipSuccess but ignore cache setting for now (API allows this).
Fixes #626.
> Fix hipFuncSetCacheConfig() doesn't return hipSuccess

- CMakeLists.txt
- cmake/UnitTests.cmake
- scripts/checkv2.py
- scripts/unit_tests.sh
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
Implement HIP/CUDA stream semantics using dependency chains via `LastEvent` as opposed to barriers. `Queue::getSyncQueuesLastEvens()` gathers `LastEvent` for all the queues it's supposed to sync. Backends can then extract handles and add dependencies to all enqueue commands.
> QueueSync without barriers

- cmake/UnitTests.cmake
- src/backend/OpenCL/CHIPBackendOpenCL.cc
OpenCL BE: Do not pass -x spir
'-x spir' requests compilation of the old SPIR 1.2/2.0 whereas we use the new SPIR-V which doesn't need the build flag, as long as we call clCreateProgramWithIL(). This we do via the C++ wrapper.
Passing -x spir might fail if the device doesn't support the old SPIR even though it might support the new SPIR-V.
> OpenCL BE: Do not pass -x spir

- src/CHIPBindings.cc
- src/backend/Level0/CHIPBackendLevel0.cc
Previously a cmake option was introduced but the original work around was not removed.
> remove the old first-touch workaround

- src/CHIPBackend.hh
- src/CHIPBindings.cc
OpenCL calls MemMap/MemUnmap. This results in queue operations inside hipMalloc, etc.
Also seems to decrease the unit test runtime from 17s to 1s which matches Level Zero performance. 
Fixes #657
> Additional mutexes 

- cmake/UnitTests.cmake
- scripts/check.py
- scripts/unit_tests.sh
* Exclude a couple of tests which were found to be flaky. 
* For OpenCL, there is a set of tests which sometimes timeout when tests are run parallel. Sometimes these tests explode in time taken to complete - from 15s to 1500s, for example. If you set `--repeat until-fail:10` it's almost guaranteed that some of them will timeout. 
* Most of these tests seem to involve managed memory. 
* hipEventRecord sometimes reports negative time for OpenCL
This needs to investigated, but for now let's just run these tests in a single thread to get the CI system to be more stable.
> Identify tests which timeout when run in parallel

- bitcode/devicelib.cl
- cmake/UnitTests.cmake
- include/hip/devicelib/integer/int_intrinsics.hh
- scripts/check.py
- scripts/unit_tests.sh
- tests/runtime/CMakeLists.txt
- tests/runtime/TestBitInsert.hip
Note that they are made available by passing -DCHIP_ENABLE_NON_COMPLIANT_DEVICELIB_CODE to HIP compilation.
> Resurrect __bitinsert_u32, implement __bitinsert_u64

- include/hip/spirv_hip_vector_types.h
Adjust a HIP header for avoiding single element vectors to appear in LLVM IR. Single element vectors are not supported in SPIR-V without an extension (e.g. SPV_INTEL_vector_compute) which are enabled with hard coded --spirv-ext=+all option in clang. 
I'll make clang patch to disable all SPIR-V extension which will cause an assertion to be triggered in `llvm-spirv` if there are single element vectors in the input device code.
Related to issue #713.
(We had this patch previously but it got lost in #521)
> SPIR-V portability fix for single element vectors

- include/hip/devicelib/double_precision/dp_math.hh
- include/hip/devicelib/single_precision/sp_math.hh
- tests/compiler/CMakeLists.txt
- tests/compiler/TestFastMath.hip
Map HIP device builtin functions to corresponding OpenCL native built-ins on -ffast-math. The rationale is based on `-ffast-math` specification [1] which gives permission to approximate transcendental functions (-fapprox-func).
[1] https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffast-math
> Add mapping to OpenCL native_* on -ffast-math

- .github/actions/get-shas/action.yml
- .github/workflows/presubmit.yml
- README.md
- bitcode/CMakeLists.txt
- bitcode/ballot_native.cl
- bitcode/devicelib.cl
- scripts/configure_llvm.sh
- scripts/unit_tests.sh
- src/CHIPBackend.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/spirv.cc
- tests/runtime/CMakeLists.txt
- tests/runtime/TestBallot.hip
Both the level zero and the OpenCL implementations may support SPIR-V counterpart of __ballot() below SPIR-V v1.3 with appropriate extension.
However, there does not seem to be a way to produce SPIR-V with ballot instructions on version v1.2 and below without using chipStar's fork of the llvm-spirv. To get around this limitation the ballot() is put into separate source, compiled to SPIR-V v1.3 and linked at runtime if the device supports it. Consequently, this patch should make the llvm-spirv fork unneeded.
> Link __ballot() implementation at runtime

- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
Fix hipInitFromNativeHandles() resetted properties in the backend which caused a linking issue seen in #735.
Resolves #735.
> level0: resolve #735

- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
Fix bogus sizeof(sizeof(string)) expression, which results in gcnArchName() returning "unavailable" truncated to 8 characters, which is "unavaila".
> Fix bogus sizeof(sizeof(string)) expression in gcnArchName()

- cmake/FindLLVM.cmake
- cmake/UnitTests.cmake
- samples/hipMultiThreadAddCallback/hipMultiThreadAddCallback.cc
- samples/hip_sycl_interop/onemkl_gemm_wrapper/onemkl_gemm_wrapper.cpp
- samples/hip_sycl_interop_no_buffers/onemkl_gemm_wrapper_no_buffers/onemkl_gemm_wrapper.cpp
- scripts/check.py
- scripts/unit_tests.sh
- src/CHIPBackend.cc
- src/backend/Level0/CHIPBackendLevel0.cc
* CI now loads icpx and mkl in order to build HIP-SYCL Interop
* HIP-SYCL Interop samples now query env for whether immediate or regular command lists are used
* Fix FindLLVM - don't cache value if not found. You no longer need to rm CMakeCache.txt to reconfigure if llvm wasn't loaded
> Add MKL back into testing for interop

- tests/runtime/CMakeLists.txt
- tests/runtime/TestBallot.hip
- tests/runtime/TestIndirectMappedHostAlloc.hip
Fix tests under `tests/runtime/` were unintentinally skipped in debug builds due to word "SKIP" appearing in the chipStar's debug prints. More specifically, the tests were skipped due to `CHIP debug ... : CHIP_SKIP_UNINIT=...` messages.
Fixed the issue by changing the skipping logic to be exit code based.
> Fix tests were unintentinally skipped

- CMakeLists.txt
- samples/CMakeLists.txt
- samples/hipAddCallback/CMakeLists.txt
- samples/hipAddCallback/hipAddCallback.cc
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPDriver.hh
- src/CHIPException.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
Various small changes mostly related to development and cleanup
* Add CHIPERR_CHECK_LOG_AND_ABORT macro
* Add `CHIP_L0_EVENT_TIMEOUT` environment variable. Once this timeout is reached during `zeEventHostSynchronize`, abort will be called a stack trace will be generated. 
* Add a new single thread callback sample
* Context destructor will now print % reuse for command lists and events
> Various improvements

- samples/hipMultiThreadAddCallback/hipMultiThreadAddCallback.cc
- scripts/check.py
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
* Fix event refcounts
* Switch to using an event stack for handling events inside an event pool
* Event pools now start small and double as needed to prevent generation of many events for small test cases
* Get rid of `CallbackEventMonitor` and use a single thread to handle all other activities such as event monitoring, callbacks, event pool management (if needed in the future)
* replace all "Event use after delete" asserts with a new function `isDeletedSanityCheck()` which does nothing in `Release`. Call this function at every event member function. 
* check.py add `--total-runtime=x` option. Given a number of minutes, run tests once to estimate the runtime and then calculate the `--num-tries` to fill the time allotted.
> Dynamic event pools

- .github/workflows/clang-tidy-format.yml
Linter no longer recognized "main" as a proper version
> Update cpp-linter-action version

- bitcode/CMakeLists.txt
- bitcode/c_to_opencl.c
- bitcode/c_to_opencl.def
- bitcode/devicelib.cl
- include/hip/devicelib/double_precision/dp_math.hh
- include/hip/devicelib/single_precision/sp_math.hh
Map a set of HIP built-ins referenced by HeCBench benchmarks to compiler built-ins. The myocyte-hip benchmark seems to benefit from this the most - most likely due to:
* HIP built-in calls with compile time values which are constant-folded.
* HIP built-in calls which are simplified such as `pow(x, 2) --> x*x`.
> Map device built-ins to compiler built-ins

- samples/hipKernelLaunchIsNonBlocking/hipKernelLaunchIsNonBlocking.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
Remove redundant exit check from checkCallbacks
> Level-zero-premature-exit

- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
Fences are more fine-grained synchronization primitives offering potentially better performance since it allows other command lists to continue, as opposed to `zeCommandQueueSynchronize` which will hold the host until all work inside the queue is complete.
* Create a fence object for every L0 Queue
* `executeCmdListReg` will reset this fence and set it to trigger upon new invocation of command list execution.
* `Queue::finish()` will wait for this fence to signal.
> Use a fence for syncing RCL 

- samples/hip_sycl_interop/onemkl_gemm_wrapper/onemkl_gemm_wrapper.cpp
- samples/hip_sycl_interop_no_buffers/onemkl_gemm_wrapper_no_buffers/onemkl_gemm_wrapper.cpp
- scripts/unit_tests.sh
Since we never return an immediate command list even when they are used internally we can just drop the check. 
There was a bug in the initial implementation where `isImmCmdList = true` but it seems that we don't really need to check if ICL is used since we never return a command list.
> SYCL-HIP Interop - Drop RCL/ICL Quer

- cmake/UnitTests.cmake
- src/CHIPBackend.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
* Skip event tracking for OpenCL
* `addDependenciesQueueSync` copied from Level Zero. TODO: bring this up to chipstar level
* Cuda tests are flaky but this was also confirmed on main so not new failures just previously didin't trigger
* Some additional 3D tests were labeled as failing for only certain platforms but turns  out to fail for all just very very rarely.
> OpenCL Event Cleanup

- CMakeLists.txt
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/backend/OpenCL/MemoryManager.cc
* Fix passed USM pointers to clSetKernelExecInfo() as CL_KERNEL_EXEC_INFO_SVM_PTRS which resulted in CL_INVALID_VALUE error on couple Intel OpenCL implementations.
* Fix indirect USM pointers were not annotated (correctly).
Also, refactor SVMMemoryRegion -> MemoryManager as the class may host either SVM or USM allocations.
> OpenCL: Fix indirect USM pointer related issues

- docs/Using.md
- src/CHIPBackend.cc
- src/CHIPBindings.cc
- src/CHIPDriver.hh
- tests/runtime/TestLazyModuleInit.cpp
With CHIP_LAZY_JIT=0 setting, all device modules will be compiled at chipStar runtime initialization. We have used this in benchmarking to exclude device compilation time in kernel execution time measurements.
> Add CHIP_LAZY_JIT environment option to control JIT timing

- src/spirv.cc
For accepting SPIR-V modules of higher versions than v1.2. The backend drivers probably already check the SPIR-V version of the modules during device compilation so the check was probably redundant too.
> Remove SPIR-V version check in the parser

- include/hip/hip_interop.h
- samples/hip_async_interop/BinomialOption.cpp
- samples/hip_async_interop/BinomialOptionLevel0.cpp
- samples/hip_async_interop/BinomialOptionOpenCL.cpp
- samples/hip_sycl_interop/hip_sycl_interop.cpp
- samples/hip_sycl_interop/hip_sycl_interop.h
- samples/hip_sycl_interop/onemkl_gemm_wrapper/onemkl_gemm_wrapper.cpp
- samples/hip_sycl_interop_no_buffers/hip_sycl_interop.cpp
- samples/hip_sycl_interop_no_buffers/hip_sycl_interop.h
- samples/hip_sycl_interop_no_buffers/onemkl_gemm_wrapper_no_buffers/onemkl_gemm_wrapper.cpp
- samples/sycl_hip_interop/sycl_hip_interop_driver/sycl_chip_interop.cpp
- scripts/check.py
- src/CHIPBindings.cc
- src/CHIPDriver.cc
- src/CHIPDriver.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
Refactor how backend handles are returned. `hipGetBackendNativeHandles` is now to be called twice - once to get the number of handles and second time to populate the allocated handle array.
> Backend handles refactor

- cmake/UnitTests.cmake
* Some tests were marked as flaky for one platform but actually fail for multiple
* remove CHIP_USE_INTEL_USM test exclusion since this use of this macro is not added to the CI. Furthermore, the tests fail even without this macro.
> Fixup exluded tests

- README.md
- docs/Using.md
This add the following two points to the documentation.
1. Document existance and usage of the `CHIP_DEVICE_TYPE` environment variable.
2. Adds one more note regarding availability of trace and debug log level information.
Thanks for this great library, works great!
I had to spent some hours at the beginning tracking down the root for the following two error messages using OpenCL backend: `Selected OpenCL device 0 is out of range`.
It took some time to find the undocumented environment variable which caused chipStar to only look for GPUs on my CPU-only system.
> Add CHIP_DEVICE_TYPE to documentation

- include/hip/devicelib/single_precision/sp_intrinsics.hh
The [use-compiler-builtins](https://github.com/CHIP-SPV/chipStar/pull/763) patch unintentionally redirected HIP single precision intrinsic calls to double precision compiler/OpenCL built-ins.
> Fix HIP float intrinsics were mapped double built-ins

- docs/Using.md
There was `c` missing at the end of the name of the cuda compiler script. This corrects that typo.
Also separates the two methods to compile cuda files into paragraphs.
> fix name of the cuda compiler script

- CMakeLists.txt
- cmake/UnitTests.cmake
- samples/hipKernelLaunchIsNonBlocking/hipKernelLaunchIsNonBlocking.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/backend/OpenCL/MemoryManager.cc
PVC platforms seems to benefit a lot from the USM. Few picks:
* HeCBench/mandelbrot: 56x speed-up.
* HeCBench/floydwarshall: 14x speed-up.
* HeCBench/bitonic-sort: 33x speed-up.
* HeCBench/nw: 20x speed-up.
* HeCBench/fft: 11x speed-up.
* And bunch of other HeCBench cases with speed-ups between 1.16x and 6.5x.
The OpenCL backend still falls back to use SVM (the previous default) when the USM is not available.
> OpenCL BE: set CHIP_USE_INTEL_USM on by default

- CMakeLists.txt
- samples/CMakeLists.txt
- samples/cuda_samples/CMakeLists.txt
- samples/hip_async_interop/CMakeLists.txt
- samples/hip_sycl_interop/CMakeLists.txt
- samples/hip_sycl_interop_no_buffers/CMakeLists.txt
- samples/shuffles/CMakeLists.txt
- samples/sycl_hip_interop/sycl_hip_interop_driver/CMakeLists.txt
- tests/runtime/CMakeLists.txt
* add `CHIP_PROFILE_TESTS` option
* Most samples modify `add_test()` such that they're run through `HIP_PROFILE_TESTS_COMMAND` which in our case is iprof
* Allows for profiling tests and collecting traces from issues that arise only when things are run in parallel through ctest
> Sample and Test Profiling

- src/CHIPBackend.cc
- src/CHIPBindings.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/logging.hh
A patch set for reducing kernel launch overheads. These improved HeCBench's mrc, floydwarshall and overlay benchmarks by 41-57% on PVC.
* Skip kernel info string construction when it is not going to be logged/displayed.
* Reduce kernel launch overhead from `__hipPushCallConfiguration()` and `__hipPopCallConfiguration()` functions:
* Remove unnecessary backend initialization (backend will be initialized at `hipLaunchKernel()`).
* Avoid creating short living temporary, heap allocated `chipStar::ExecItem`.
* Exit earlier from `prepareDeviceVariablesNoLock()`.
* Recycle OpenCL kernel handles instead of creating them for each exec-item.
> Changes to reduce kernel launch overheads

- src/SPVRegister.cc
Remove confusing "A device function is already registered and mapped to a different module" warning. It just happens to be that there may be multiple __hipRegisterFunction() calls to register same functions due to the way the code is generated for the inline and template functions. There is a bit more details in the code.
> Remove a confusing already registered and mapped warning

- cmake/UnitTests.cmake
- samples/hip-cuda/FloydWarshall/CMakeLists.txt
- samples/hip_async_interop/CMakeLists.txt
- scripts/check.py
- scripts/unit_tests.sh
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/hipCtx.hh
Refactor Level Zero
* Refactor addDependenciesQueueSync
- Returns a std::pair of events to sync with and a locked mutexes
* Return more things by reference
* Refactor mutexes
- Add QueueAddRemoveMtx
- Add GlobalLastEventMtx
- Fix getOrCreateModule race condition causing segfaults
* Refactor CHIPQueueLevel0::recordEvent
- Fix bugs causing events being reported as not ready
* Refactor CHIPQueueLevel0::createCallbackData
- Fix bugs causing deadlocks
- Simplify implementation
* Drop Separate testing of regular command lists
- Since we use both regular and immediate command lists, and since using the regular 	command lists as the default execution path is less efficient than using immediate command lists, drop the testing. Subsequent PR will remove `CHIP_L0_IMM_CMD_LISTS` option.
> Level Zero Refactor + Bugfixes

- docs/Using.md
- src/CHIPDriver.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
Enabling queue profiling by default slow down kernel enqueue API calls according to vtune, at least, on Intel OpenCL targeting Intel ARC A750. Disabling the profiling improved some HeCBench cases on the device:
* overlay-hip: ~1.80x speed up.
* floydwarshall-hip: ~1.47x speed up.
* tqs-hip: ~1.13x speed up.
This patch creates queues with and without profiling and the non-profiling one is used at start. The BE switches to use the profiling queue when needed. Note, there is only transition from non-profiling queue to profiling one but not back.
Also, add environment variable for forcing queue profiling to be disabled.
> OpenCL: Use non-profiling queue, switch to profiling when needed 

- scripts/configure_llvm.sh
* Clone chipStar's fork of LLVM to match root README.md instructions.
* Fix mix-up of SPIRV_BRANCH and TRANSLATOR_BRANCH.
* `git br ...` -> `git branch ...`. The br command alias does not seems to be available in some git versions.
* Fix static library build option lacked `-DLLVM_ENABLE_ASSERTIONS=On` (assuming it's desired since the dynamic library option has it).
* Fix the script failed on SPIR-V translator branch checkout when runnig the script on already cloned LLVM.
Fixes #834.
> Fixes scripts/configure_llvm.sh

- cmake/UnitTests.cmake
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- tests/known_failures.yaml
- tests/runtime/CMakeLists.txt
- tests/runtime/CatchMemLeak1.hip
OpenCL backend called ´chipstar::Event::addDependency()´ without ever calling ´chipstar::Event::releaseDependencies()` during HIP application's lifetime and this had two possible outcomes:
1) Crash due to out of memory error because the unreleased event objects. This occured after a HIP program had streamed enough commands - like >30000 kernels.
2) Crash due to stack overflow at program exit / chipStar uninitialization. Because the event dependencies were not released, this led to a build up of very long event dependency chain. At uninitialization, the destruction of a Queue's last event led to destruction of its dependent events which led to destruction their dependend events and this possibly kept going until the crash which was caused by stack overflow from numerous call frames.
Both …
> OpenCL: Fix memory leak / OoM and stack overflow

- include/hip/spirv_channel_descriptor.h
- include/hip/spirv_texture_functions.h
- src/CHIPBackend.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- tests/known_failures.yaml
* OpenCL: Fix used device pointer as source image data for `clEnqueueWriteImage()` which is not (guaranteed) to work unless it points to fine-grained SVM allocation.
* Fix `get1DRegion()` had unrelated parameter which effectively caused element size to be ignored.
* spirv_channel_descriptor.h had multiple `hipCreateChannelDesc()` specializations setting incorrect `hipChannelFormatKind` value. Fix by importing the more recent `hipCreateChannelDesc()` implementations from the original source (hipamd).
* Fix miswiring in the `DEF_TEX2D_VEC4` macro.
> Fix bunch texture cases

- cmake/mkl_and_icpx.cmake
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/CHIPDriver.cc
- src/CHIPDriver.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/hipCtx.hh
* Fix the issue where not all events were being recycled by Level Zero event collector
* Refactor `CHIPEventLevel0::wait()` to get rid of race conditions reported by valgrind. The API states that calls to `zeEventHostSynchronize` and `zeEventQuery` are thread safe but valgrind reports race conditions.
* Implement a global shared mutex - `ApiMtx` which is to be locked by every HIP API call. This prevents multiple HIP commands from executing at the same time. Pretty coarse lock which we can relax over time since performance is affected only for multithreaded HIP applications of which I haven't seen any yet.
> Level Zero - Fix OOM & Improve Thread Safety

- bitcode/README-devicelib.md
- bitcode/atomicAddDouble_emulation.cl
- bitcode/atomicAddDouble_native.cl
- bitcode/atomicAddFloat_emulation.cl
- bitcode/atomicAddFloat_native.cl
- bitcode/cl_utils.h
- include/hip/devicelib/atomics.hh
A issue discovered while running HIP programs on OpenCL-BE->rusticl (with #830). Linking of __chip_atomic_add_f* symbols failed because the caller's and callee's function signature differed by their pointer parameters (pointee type didn't match).
The mismatch was caused by LLVM-SPIRV-Translator's feature that attempts to recover original pointee types in LLVM bitcodes that use opaque pointers. But the way it attempts to infer the types may end up with SPIR-V functions with different pointee type across SPIR-V modules.
The issue is worked around by passing pointers as integers for functions whose definitions are linked in at runtime.
> rtdevlib: fix function signature mismatches

- docs/Using.md
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/CHIPDriver.hh
- src/SPVRegister.cc
- src/SPVRegister.hh
- src/Utils.cc
- src/Utils.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/backend/OpenCL/MemoryManager.cc
- src/common.hh
- src/spirv.cc
- tests/known_failures.yaml
- tests/runtime/CMakeLists.txt
- tests/runtime/TestBufferDevAddr.hip
Use [cl_ext_buffer_device_address](https://github.com/pocl/pocl/blob/1f80005557222a35f44a7d0d076aa4ae86499bdc/include/CL/cl_ext_pocl.h#L69) extension (experimental at the time
of this commit) for managing HIP device allocations on devices where neither USM
nor SVM is available. The latest main of POCL and, hopefully soon,
Mesa's rusticl supports this extension. Briefly, the extension enables
the OpenCL backend to pin cl_mem buffers to device memory and obtain their
fixed addresses.
The extension has a down side that the addresses of the device and
host allocations may alias, thus, we can't automatically determine
copy direction in `hipMemcpy*(, hipMemcpyDefault)` calls. For this
reason the unified [virtual] addressing feature is set off and,
consequently, hipMemcpyDefault is unsupported …
> OpenCL: Support devices with cl_ext_buffer_device_address

- cmake/hip-config-in.cmake
- scripts/unit_tests.sh
- tests/CMakeLists.txt
* Update H4I submodules to resolve hipblas.h conflicts. Fix the use of cmake `option` keyword
* Export `HIP_VERSION` to `hip-config.cmake`
> [HipBLAS] Fix hiblas.h and hipsolver header conflicts

- include/hip/devicelib/double_precision/dp_math.hh
Fixed the typo in double-precision math function j1 so that it calls __ocml_j1_f64 instead of __ocml_j0_f64.
> Fix math function j1 typo in dp_math.hh

- include/cuspv/cuda_runtime.h
The cudaMallocManaged function in cuda_runtime.h is defined with 1st parameter in type void**, which leads to the following compilation errors when passing arguments. (This compilation error is from nbnxm-cuda benchmark in HeCBench, a reproducer is included in the end.)
```
main.cu:409:3: error: no matching function for call to 'cudaMallocManaged'
409 |   cudaMallocManaged(&a_xq, sizeof(Float4) * NUM_ATOMS);
|   ^~~~~~~~~~~~~~~~~
/home/tsaini.chen/install/chipStar/chipStar_06052024/include/cuspv/cuda_runtime.h:778:27: note: candidate function not viable: no known conversion from 'Float4 **' (aka 'HIP_vector_type<float, 4> **') to 'void **' for 1st argument
778 | static inline cudaError_t cudaMallocManaged(void **DevPtr, size_t Size,
|                           ^ …
```
> fixed cudaMallocManaged function parameter type issue

- CMakeLists.txt
- host_math_funcs/CMakeLists.txt
- host_math_funcs/common.h
- host_math_funcs/ep.h
- host_math_funcs/mathD.h
- host_math_funcs/mathF.h
- host_math_funcs/mathH.h
- host_math_funcs/opts.h
- host_math_funcs/privD.h
- host_math_funcs/privF.h
- host_math_funcs/privH.h
- include/hip/devicelib/host_math_funcs.hh
- include/hip/spirv_hip_devicelib.hh
- samples/cuda_samples/6_Advanced/mergeSort/mergeSort_host.cpp
- tests/compiler/CMakeLists.txt
- tests/compiler/invalid-bitwidth-128.hip
- tests/known_failures.yaml
- tests/runtime/CMakeLists.txt
- tests/runtime/host-math-funcs.hip
Implement missing host math funcs
* Compiling the bitode library to host code leads to linking errors
some of the OpenCL natives being used in the library code are not
available for the CPU, resulting in linking errors
* OCML does not meant to be compiled in C++ mode
for this, we create a drop-in opencl header defining the missing
datatypes
* Since OCML uses headers in the same directory as the source files,
we must copy the necessary source files into a new directory so that
our replacement headers get picked up instead of the originals
* Implement a new header for mapping math funcs to host-side ocml
* Discover an additional way to trigger 128 bit error
* Discover a discrepancy in host and device func results
> Implement missing host-side math functions

- src/CHIPException.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/zeHipErrorConversion.hh
The zeHipErrorConversion.hh header file was created to support ze_result_t to hipError_t runtime error conversion. The header file provides the following components:
(1) A type alias that defines  `ze_hip_error_map_t` type as an unordered_map that maps ze_result_t to hipError_t
(2) A macro, `CHIPERR_CHECK_LOG_AND_THROW_TABLE`, that does exactly what `CHIPERR_CHECK_LOG_AND_THROW` does, but instead of taking a specific errtype to throw, `CHIPERR_CHECK_LOG_AND_THROW_TABLE ` takes a map of type `ze_hip_error_map_t` and use it to convert ze_result_t to corresponding hipError_t. Either the default map (`DEFAULT_ZE_HIP_ERROR_MAP`) or a custom map can be used.
An example to create a custom map:
```
ze_hip_error_map_t myMap = {
{SOME_ZE_RESULT_T, SOME_HIPERROR_T},
{SOME_ZE_RESULT_T, …
```
> Adding runtime error conversion for Level0 backend

- include/hip/spirv_hip_fp16.h
- include/hip/spirv_math_fwd.h
Partially updated the `spirv_hip_fp16.h` based on rocm release 6.1.0 and added the needed ocml functions to `spirv_math_fwd.h` (tested the ocml functions and worked well).
The parts of spirv_hip_fp16.h left unmodified includes:
- Updates in macros defined in other header files
- Left unchanged as it may impact multiple other header files
- For example, `#if __HIP_CLANG_ONLY__` was updated to `#if defined(__clang__) && defined(__HIP__)` in the new release
- \#includes for AMD-specific header files
- Did not include the header files such as <hip/amd_detail/amd_hip_common.h> and "hip/amd_detail/host_defines.h" (it seems like we do have our host_defines.h in chipStar, but it seems to still be in progress)
- Newly added shuffle functions
- Did not add the shuffle functions from new header in …
> spirv_hip_fp16.h header file updates

- .github/workflows/publish-docker.yml
- scripts/unit_tests.sh
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- tests/known_failures.yaml
Fixes #859
* Kernel annotation is skipped - seems like an OpenCL CPU runtime issue
https://community.intel.com/t5/OpenCL-for-CPU/OpenCL-Using-USM-on-Intel-CPU-Runtime-along-with/m-p/1621136#M7350
https://github.com/intel/compute-runtime/issues/748
* Remove LLVM15 Testing from CI
* Re-enable OpenCL CPU CI
> skip kernel annotation on CPU

- src/backend/OpenCL/CHIPBackendOpenCL.cc
- src/backend/OpenCL/CHIPBackendOpenCL.hh
- src/backend/OpenCL/MemoryManager.cc
- src/backend/OpenCL/clHipErrorConversion.hh
Once kernels are annotated with `CL_KERNEL_EXEC_INFO_USM_PTRS_INTEL`, they need to be annotated with `CL_KERNEL_EXEC_INFO_INDIRECT_DEVICE_ACCESS_INTEL`, if the arguments inside the kernel which might see indirect access are allocated as `device`. If multiple types of allocations are used we have to have multiple calls to `clSetKernelExecInfo`.Optimally, we would inspect the kernel to figure out exactly what kind of allocations have been used but with indirect access it's complicated.
> Properly annotate Intel USM kernels

- .github/workflows/check-unit-tests-intel.yml
- README.md
- cmake/FindLLVM.cmake
- llvm_passes/HipAbort.cpp
- llvm_passes/HipEmitLoweredNames.cpp
- llvm_passes/HipGlobalVariables.cpp
- llvm_passes/HipIGBADetector.cpp
- llvm_passes/HipKernelArgSpiller.cpp
- llvm_passes/HipLowerZeroLengthArrays.cpp
- llvm_passes/HipPasses.cpp
- llvm_passes/HipPrintf.cpp
- llvm_passes/HipSanityChecks.cpp
- llvm_passes/HipStripUsedIntrinsics.cpp
- llvm_passes/HipTextureLowering.cpp
- llvm_passes/HipWarps.cpp
- llvm_passes/SPIRVImageType.cc
- scripts/configure_llvm.sh
- scripts/unit_tests.sh
* Fixed LLVM passes for LLVM-19.
* Changed chipStar configuration to prefer llvm-spirv with version suffix which matches to the chosen LLVM (e.g. `llvm-spirv-19`).
* Update README and scripts/configure_llvm.sh.
* New in clang-19: clang's SPIR-V and HIPSPV toolchain picks `llvm-spirv-XX` (when found in PATH or installed alongside the clang binary) where XX matches to the clang's major version. This should resolve the llvm-spirv issue reported in #824.
TODOs before the PR is ready for landing:
> Make adjustments for LLVM-19

- tests/known_failures.yaml
- tests/runtime/CMakeLists.txt
- tests/runtime/host-math-funcs.hip
Fixes #890
* __ocml_log_64 seems to be giving incorrect results?
* BUILTIN_CLASS_F32/64 gives incorrect rusult or causes 128 bit error
> Fix device-side functions

- samples/hipStreamSemantics/hipStreamSemantics.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- tests/known_failures.yaml
* Don't lock event mutex for hipStreamDestroy
Fixes #813
> hipStreamSemantics Fixes

- CMakeLists.txt
- README.md
- bin/cucc.py
- cmake/FindLLVM.cmake
- docker/DockerfileBase
- docker/DockerfileLatest
- samples/CMakeLists.txt
- samples/fp16/CMakeLists.txt
- scripts/configure_llvm.sh
- src/CHIPBackend.cc
- src/CHIPBackend.hh
- src/CHIPBindings.cc
- src/CHIPException.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- tests/known_failures.yaml
* Remove unnecessary __future__ import from cucc
* Update configure_llvm.sh
* Disable some samples/tests for RISC-V
* Dump trace on abort
* HIP - SYCL interop Level Zero: queue sync only upon ownership. Required on ALCF systems
* various format & small fixes, cleanup
Fixes #920
> ChipStar-1.2-rc1 fixes

- .github/workflows/presubmit.yml
- README.md
- src/CHIPDriver.hh
- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
- tests/devicelib/sincospifSpotTest.cc
- tests/known_failures.yaml
- tests/runtime/TestRecordEventBlocking.cpp
* Implement CHIP_MODULE_CACHE_DIR
> Module Caching

- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/OpenCL/CHIPBackendOpenCL.cc
Always print the JIT log result. It appears to be always empty upon success but warning might be printed also might be vendor specific.
> Print JIT logs to Info, always

- src/backend/Level0/CHIPBackendLevel0.cc
- src/backend/Level0/CHIPBackendLevel0.hh
Perform memory copy and fill via dedicated copy command list
> Use Level Zero Copy Queues

- src/spirv_hiprtc.cc
Thank you for maintaining the awesome project! This PR adds support for `-I` option in hipRTC API to support specifying include directories.
To share the context: I was trying to use chipStar in CuPy (https://github.com/cupy/cupy/pull/8700). CuPy compiles generated kernels through NVRTC/hipRTC, which require headers from directories specified by `-I`.
> Support specifying include directories (`-I`) through hipRTC

- bitcode/devicelib.cl
Fix SPIR-V Erros where caller and callee types don't match
> fix __ocml_cvtrtn_f16_f32

- samples/hip_sycl_interop/onemkl_gemm_wrapper/onemkl_gemm_wrapper.cpp
- samples/hip_sycl_interop_no_buffers/onemkl_gemm_wrapper_no_buffers/onemkl_gemm_wrapper.cpp
Fixes #959
[] merge https://github.com/CHIP-SPV/H4I-MKLShim/pull/24
> MKLShim Support for OneAPI 2025

- CMakeLists.txt
This changes CMakeLists.txt so that SPIRV-Tools is linked with CHIP target with a private scope. This avoids the case of dependencies of CHIP also needing libSPIRV-Tools.a to be linked in (but leaves CHIP target itself still needing SPIRV-Tools).
> Small modification to CMakeLists to link with SPIRV-Tools with a private scope

- scripts/configure_llvm.sh
- tests/compiler/CMakeLists.txt
- tests/compiler/rdcLink/CMakeLists.txt
- tests/compiler/rdcLink/TestStaticLibRDC.bash
- tests/compiler/rdcLink/k.cu
- tests/compiler/rdcLink/k.h
- tests/compiler/rdcLink/k1.cu
- tests/compiler/rdcLink/t.cpp
> Static Device Library support + llvm configure fix

- samples/hip_sycl_interop/onemkl_gemm_wrapper/onemkl_gemm_wrapper.cpp
- samples/hip_sycl_interop_no_buffers/onemkl_gemm_wrapper_no_buffers/onemkl_gemm_wrapper.cpp
With the 2025.0.5 compilers on Aurora, chipStar fails to build since it does not use the correct `sycl::detail::make_platform` etc. APIs.
It currently checks whether the UR API is used by checking `ifdef ur_native_handle_t` (https://github.com/CHIP-SPV/chipStar/blob/f0b992e2b7b9fc0c0f153e0e728ea0fd132d6de9/samples/hip_sycl_interop/onemkl_gemm_wrapper/onemkl_gemm_wrapper.cpp#L29). However, `ifdef` doesn't work to check if a typedef is defined, so it’s not working as expected (https://stackoverflow.com/questions/6772802/in-c-c-is-there-a-directive-similar-to-ifndef-for-typedefs)
I double checked this with a simple example:
```
> cat t.cpp
#include <stdio.h>
typedef int myint;
int main()
{
#ifdef myint
printf(“DEF\n”);
#else
printf(“NOT DEF\n”);
#endif
return 0;
}
> icpx t.cpp
> ./a.out
NOT …
```
> Updating hip_sycl_interop examples to use ”#ifdef UR_API_H_INCLUDED” instead of "ifdef ur_native_handle_t"

- .github/workflows/check-unit-tests-intel.yml
- .github/workflows/presubmit.yml
- CMakeLists.txt
- llvm_passes/HipDynMem.cpp
- llvm_passes/HipIGBADetector.cpp
- llvm_passes/HipPrintf.cpp
- scripts/configure_llvm.sh
- scripts/manage_known_failures.py
- scripts/unit_tests.sh
- tests/known_failures.yaml
This PR introduces support for LLVM 20.
Key changes include:
* Updated GitHub Actions workflows to test with LLVM 18, 19, and 20, removing LLVM 16.
* Modified LLVM passes (HipDynMem.cpp, HipIGBADetector.cpp, HipPrintf.cpp) to adapt to LLVM 20 API changes, particularly around opaque and typed pointers, and updated IGBA detection logic.
* Updated CMakeLists.txt to pass the target LLVM major version to the manage_known_failures.py script.
* Updated scripts/configure_llvm.sh to:
* Add support for LLVM 20 and remove support for LLVM 15 and 16.
* Introduce an -N option to print the CMake configuration command without execution.
* Switch to using the CHIP-SPV fork of SPIRV-LLVM-Translator and update branch logic.
* Add CLANG_DEFAULT_PIE_ON_LINUX=off to CMake options.
* Updated …
> Add Support for LLVM 20 

- llvm_passes/HipGlobalVariables.cpp
- llvm_passes/HipPromoteInts.cpp
- llvm_passes/HipPromoteInts.h
- tests/compiler/promoteInt/CMakeLists.txt
- tests/compiler/promoteInt/loads.ll
- tests/compiler/promoteInt/rocprim.ll
- tests/compiler/promoteInt/run_promote_int_pass.bash
- tests/compiler/promoteInt/signed_constant_compare.ll
- tests/known_failures.yaml
- During testing of rocprim, some cases of unresolved nonstd types were found
- Extracted an IR reproducer from rocprim & added it as a test case
- Source of error in PHI node processing
- Add examples and more comments, especially regarding handling of PHI nodes
- PHI nodes special handling for incoming blocks being trunc or zext
- Defer handling of incoming values until they've been processed/promoted
> Refactor HipPromoteInt Pass

- samples/hip_sycl_interop/onemkl_gemm_wrapper/onemkl_gemm_wrapper.cpp
- samples/hip_sycl_interop_no_buffers/onemkl_gemm_wrapper_no_buffers/onemkl_gemm_wrapper.cpp
With MKL version 20250001 on Aurora, it looks like the Level Zero backend needs all devices to be in the context for the MKLshim and interop with MKL layer to work.
It will run regular parallel_for kernels fine, but I see this error for calling hipBlas functions:
```
MKL Warning: Incompatible OpenCL driver version. GPU performance may be reduced.
Caught synchronous SYCL exception during GEMM:
Level-Zero error:700000041879048196
On device: 'Intel(R) Data Center GPU Max 1550'
in kernel: oneapi::mkl::blas::sgemm_incopy
```
From looking at the trace, the MKL module is failing at build time from: 
```
01:29:51.286082254 - x4204c0s1b0n0 - vpid: 177150, vtid: 177150 - lttng_ust_ze_build:log: { buildLog: "error: Kernel compiled with required subgroup size 8, which is unsupported on this platform …
```
> Updates for UR API with LevelZero backend for MKL

- samples/hip_sycl_interop/hip_sycl_interop.cpp
- samples/hip_sycl_interop_no_buffers/hip_sycl_interop.cpp
As mentioned in https://github.com/CHIP-SPV/chipStar/pull/998, it looks like the  hip_sycl_interop tests to return zero even when they return the wrong answer. This changes the tests to return non-zero if they fail validation. If there's a better way to do this, feel free to do that instead.
> Changing hip_sycl_interop tests to return non-zero if they fail

- README.md
- tools/opencl-spirv-compiler/opencl-spirv-compiler.cpp
- tools/spirv-extractor/spirv-extractor.cc
- tools/spirv-extractor/spirv-extractor.hh
- Add --validate flag to spirv-extractor
- Add documentation for spirv-extractor and opencl-spirv-compiler tools
- Fix typo in README: hipFTT → hipFFT
- Update README LLVM version compatability information
> Add SPIR-V validation to extractor and improve file detection

- llvm_passes/HipPrintf.cpp
- llvm_passes/HipSanityChecks.cpp
- src/SPIRVFuncInfo.hh
Not the proper solution, since it'd require proper check in clang's sema.
The goal of this change was to add some context and shed some light on what's really going on.
Without this changes `HipPrintf` will crash due to assert without much of a context.
Thus figuring it out what's wrong requires debugger session and `->dump()`'ing IR.
- Added check for `InlineAsm` `llvm::Value` to `HipSanityChecks` pass aborting issuing warning (and aborting  in debug)
- Fixed crasher in `HipPrintf` pass on `CallInst` with inline assembly
SPIRV translator will assert on `InlineAsm` still so validation will fail.
Also needed to add `<cstdint>` include since on this machine libstdc++ (gcc-14) needed it, didn't seem to be needed on 22.04 when compiled earlier.
I also had minor problem with cmake once I …
> Improve usability when dealing with codebase with inline assembly

- CMakeLists.txt
Since we switched to using SPIR-V Tools fork, we should use `main` tag
Also, Aurora required the use of gcc for building the tools 
Fixes #1021
> hotfix: SPIR-V Tools fork building

- src/backend/Level0/CHIPBackendLevel0.cc
As described in #1025 the spin lock is not necessary (at least for non-buggy LZ runtimes). This makes the change.
> Removing spin lock in wait()

- src/backend/Level0/CHIPBackendLevel0.cc
> Change log level from error to warning for zeEventQueryStatus duration check in CHIPEventLevel0.

- src/CHIPBackend.cc
This adds a free for an allocation of device memory in allocateDeviceVariablesNoLock.
We can see that memory on the device is allocated here: https://github.com/CHIP-SPV/chipStar/blob/c2d64dda33c8df7c064238003f37b637ffc5850c/src/CHIPBackend.cc#L361 but never freed before the function goes out of scope.
This was discovered from looking at a trace while debugging Issue https://github.com/CHIP-SPV/chipStar/issues/1035
> Adding a corresponding free for an alloc in allocateDeviceVariablesNoLock

- README.md
- llvm_passes/HipGlobalVariables.cpp
- tests/known_failures.yaml
Previously, `__constant__` variables were modeled in LLVM IR as followed, for example:
```llvm
@SomeConstant = hidden addrspace(1) externally_initialized global i32 123, align 4
```
But since LLVM-20 they are modeled as:
```llvm
@SomeConstant = hidden addrspace(1) externally_initialized constant i32 123, align 4
```
And this change makes `hipMemcpy{From,To}Symbol()` calls stop working. The shadow kernels operating on these `__constant__` variables still works (on my machine) but obviously rely on undefined behavior.
Fix the issues by removing the `constant` attribute on the `__constant__` variables.
> LLVM-20: Fix hipMemcpy{From,To}Symbol stopped working
